services:
    laravel-docker:
        container_name: galen-api
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - 8080:80

    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_docker
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
